"""Added face_encoding to Criminal model

Revision ID: 61a48e68ff27
Revises: 
Create Date: 2025-03-15 23:17:09.812539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a48e68ff27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criminal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encoding', sa.Text(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('crime_details',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('criminal', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('crime_details',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('face_encoding')

    # ### end Alembic commands ###
