"""Added enable_face_detection and enable_weapon_detection to Camera model

Revision ID: f60e74666ce9
Revises: 61a48e68ff27
Create Date: 2025-03-15 23:58:39.117073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60e74666ce9'
down_revision = '61a48e68ff27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_face_detection', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable_weapon_detection', sa.Boolean(), nullable=True))

    with op.batch_alter_table('criminal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_yolo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('yolo_model_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criminal', schema=None) as batch_op:
        batch_op.drop_column('yolo_model_path')
        batch_op.drop_column('enable_yolo')

    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.drop_column('enable_weapon_detection')
        batch_op.drop_column('enable_face_detection')

    # ### end Alembic commands ###
